name: Copy branches main to documentation 
env:
  REPO_OWNER: hannesdelbeke


# Controls when the action will run.
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copy-content-to-mkdocs-branch:
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout source repo (main branch)
        uses: actions/checkout@v2
        with: 
          path: src_repo
          
      - name: checkout target repo (mkdocs branch)
        uses: actions/checkout@v2
        with: 
          path: dst_repo
          ref: mkdocs

      - name: 1. install node for janitor
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: 2. checkout janitor
        uses: actions/checkout@v2
        with:
          repository: 'hannesdelbeke/note-link-janitor'  # use fork to support subfolders
          ref: stable
          path: 'note-link-janitor'
          
      - name: 3. install yarn in janitor workspace
        run: |
            cd ${{ github.workspace }}/note-link-janitor
            yarn install
            yarn run build
            
      - name: 4. Run Note Link Janitor
        run: ${{ github.workspace }}/note-link-janitor/dist/index.js ${{ github.workspace }}/src_repo/notes

      # first move image, then notes. # docs folder already exists, it contains css in assets
      - name: move submodule files to dst_repo
        run: |
            mkdir -p dst_repo/static/images/
            mv src_repo/notes/image/* dst_repo/static/images/
            rsync -av src_repo/notes/* dst_repo/docs/
        
      - name: push updates to mkdocs branch
        # uses: ad-m/github-push-action@master
        # with:
        #   directory: dst_repo
        run: |
            cd dst_repo
            git config --global user.name github-actions
            git config --global user.email github-actions@github.com
            git add .
            git commit -m "GITHUB ACTION 🤖⚡copy notes and images"
            git push
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: install py requirements
        run: |
            cd dst_repo
            pip install --requirement requirements.txt
            
      - name: build mkdocs & deploy to github pages
        run: |
            cd dst_repo
            mkdocs gh-deploy --force --message "GITHUB ACTION 🤖⚡ deploy site, mkdocs v{version} "